// Constants List
export const GET_BEER_SUCCESS                   = 'GET_BEER_SUCCESS';
export const GET_POPULAR_BEER_SUCCESS           = 'GET_POPULAR_BEER_SUCCESS';
export const GET_RECENT_BEER_SUCCESS            = 'GET_RECENT_BEER_SUCCESS';
export const GET_MORE_BEER_SUCCESS              = 'GET_MORE_BEER_SUCCESS';
export const GET_RANDOM_BEER_SUCCESS            = 'GET_RANDOM_BEER_SUCCESS';
export const GET_SINGLE_BEER_SUCCESS            = 'GET_SINGLE_BEER_SUCCESS';

export const GET_BEER_SEARCH_BY_NAME_SUCCESS    = 'GET_BEER_SEARCH_BY_NAME_SUCCESS';